name: "API Check during CI/CD"
description: "Check the API during CI/CD to ensure it is working as expected"
inputs:
  max_retries:
    description: "The maximum number of retries"
    required: true
    default: "100"
  retry_delay:
    description: "The delay between retries (milliseconds)"
    required: false
    default: "1000"
  url:
    description: "The URL of the API"
    required: true
    default: "https://example.com"
  method:
    description: "The HTTP method to use"
    required: true
    default: "GET"
  request_headers:
    description: "The headers to include in the request (format: \"key1=value1,key2=value\")"
    required: false
    default: ""
  request_body:
    description: "The body to include in the request (format: JSON)"
    required: false
    default: ""
  expected_pass_count:
    description: "The number of times the API should pass"
    required: false
    default: "1"
  expected_status:
    description: "The expected HTTP status code"
    required: true
    default: "200"
  expected_headers:
    description: "The expected headers in the response (format: \"key1=value1,key2=value\")"
    required: false
    default: ""
  expected_body:
    description: "The expected body in the response (format: JSON)"
    required: false
    default: ""
  timeout:
    description: "The maximum time to wait for the request to complete (milliseconds)"
    required: false
    default: "3000"
runs:
  using: "node20"
  main: "dist/index.js"


